token:
  expiration_time: 300000
  secret: '{cipher}AYAXhSuOLQEe7bmgxSmpQkGqtAKb0AxIdiA4T5g0e6j2oFpW0YGIvb0bzFe6CaO1st9+4gR8YTcQYwm7Vb1TgTX3Qiu4FSixp2/LHcxkvefmyUfaoFvzA9Pk081437LxM8eE6mM6L1R+db7eYZ3B57A6XYJup/i6uoPj45I3gqolWuCrI6ftF0oYLIoCsADhxM3XejCOlbj1Q4TfTq35ze5nSpZrfMhwsCdWJgezQ6jAA7letNsGqBEy2cLyAyV3mxW6H3bih5J5MjOCKu+rOc01oCSBG/T11/JihwiZ/MzSEhN+N+GZOrAscofvo3Q7nN2XFJ7c2DW7C4E6h8pCKCsWkeS9DPYTcJj7iWn31g6DVNet+t+2zxyNQ3JtCQbVFGJQZ2kbqV7b9hPo8lJWcE8Lc+HEEzJi2bMw7qMVrRKHqEBXi+ae2UhJuwXE4e+0QrPG9iH7NasSP7ZvewrNGfXieU6eovrogD5W0QWcANR7AOJtRAQqa47A0pDh3+LTXOKABy39vBddzTdIUUOODh3Hut/Y1mUYLspsZYqlqolYdu8/KvS9rNt+IaIG1GXLg3ADoFqQ9PEWNArJMQo8xpnoP0CY4zzRzCAiyResACpzFj3GZakQEi615JW3a4bqprE='
gateway:
  ip: "172.19.0.3"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}AYDLz+++ekvvZKR3oCYs2+z5nVh0Ck9kNlBLTBIxnjNelRV3h2sROxOSn375Z0zQJDD2lkayGf0OF/gjEFO/oEyBck686mOQJryeVEdammvF6ZDQicCkV3tENzqZkb7RPYCvLSZpinFXSLPA01q3MqFYkCnZDw0isA+gYaCczfWgo1zgcg/o6E3fd1ATFIWCMq1u6zeFgXYC0KzQh+sPHGRrJb66VWgkgQyBq6M4lwVaU4ipRjnSlAoHovppROVfujD53BT7GfYm1V+fqJp9qKx8/Nhs4zRD5+mOjfsOswJjhEQVP91nIQRzs8q3IYWUWo2XDaejNyNczpBNZKEfgN1qcZX3tnEzMWLvGy4tV61W5A10He02IEqfJ5xMo9lD28QEHEdl8LJPz3ej7qdRc17/GUAjJ/KyT3BR+RgO1vdQlGXNx6Q2E7bcWylNgmI2we9d/OcXzZl2sviR1HvAOhqLiA3f3JSCI9zRJIM30vHb2MbEj+Qh3Mlw6hlENtG90l/YMIcAQYBil6Ri4PVEOE2ACYVFCyj0AIzJIDyNkFnCTw=='

order_service:
  url: http://my-order-service/order-service/%s/orders
  exception:
    orders-is-empty: User's orders is empty.
